import { Category, Exercise } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'image-prompting',
    name: 'Image Prompting',
    icon: '🎨',
    color: '#a855f7',
    description: 'Master the art of writing AI image generation prompts for marketing visuals.',
  },
  {
    id: 'campaign-strategy',
    name: 'Campaign Strategy',
    icon: '🎯',
    color: '#3b82f6',
    description: 'Design end-to-end marketing campaign strategies for digital products.',
  },
  {
    id: 'content-planning',
    name: 'Content Planning',
    icon: '📅',
    color: '#2cbb5d',
    description: 'Plan content calendars, editorial strategies, and publishing workflows.',
  },
  {
    id: 'facebook-campaigns',
    name: 'Facebook Campaigns',
    icon: '📘',
    color: '#06b6d4',
    description: 'Build and optimize Facebook ad campaigns for digital products.',
  },
  {
    id: 'target-audience',
    name: 'Target Audience',
    icon: '👥',
    color: '#ffa116',
    description: 'Identify, segment, and profile target audiences for digital products.',
  },
];

export const EXERCISES: Exercise[] = [
  // ===== IMAGE PROMPTING (10) =====
  {
    id: 1,
    category: 'image-prompting',
    title: 'Product Hero Shot Prompt',
    difficulty: 'easy',
    points: 10,
    description: 'Write an AI image prompt that generates a compelling hero image for a SaaS product landing page.',
    prompt: 'You are launching a new project management SaaS tool called "FlowBoard". Write a detailed AI image generation prompt (for Midjourney or DALL-E) that creates a stunning hero banner image for the landing page. The image should convey productivity, collaboration, and modern design.',
    hints: ['Specify the style (photorealistic, 3D render, flat illustration, etc.)', 'Include lighting and mood descriptors', 'Mention composition and camera angle', 'Add color palette guidance', 'Include negative prompts or exclusions'],
    criteria: [{ keyword: 'style', label: 'Specifies visual style' }, { keyword: 'light', label: 'Describes lighting/mood' }, { keyword: 'color', label: 'Mentions color palette' }, { keyword: 'composition|angle|perspective|view', label: 'Defines composition' }, { keyword: 'product|saas|software|dashboard', label: 'References the product context' }],
    sample_answer: 'A clean, modern 3D render of a floating laptop displaying a colorful project management dashboard, surrounded by abstract geometric shapes representing tasks and workflows, soft gradient background transitioning from deep purple to electric blue, warm studio lighting from top-left creating subtle shadows, isometric perspective, minimal and professional aesthetic, 8K resolution, no text or watermarks.',
  },
  {
    id: 2,
    category: 'image-prompting',
    title: 'Social Media Ad Visual',
    difficulty: 'easy',
    points: 10,
    description: 'Create an image prompt for an Instagram ad promoting a fitness app.',
    prompt: 'A fitness app called "PulseTrack" needs an eye-catching Instagram ad image. Write an AI image generation prompt that would create a scroll-stopping visual suitable for a square 1080x1080 format.',
    hints: ['Think about what stops people from scrolling', 'Instagram favors vibrant, high-contrast images', 'Include human elements for relatability', 'Consider the square format constraints', 'Brand colors and energy should be evident'],
    criteria: [{ keyword: 'vibrant|bright|bold|contrast', label: 'Uses attention-grabbing visual language' }, { keyword: 'fitness|workout|exercise|athlete|sport', label: 'Relates to fitness context' }, { keyword: 'square|1080|instagram|social', label: 'Considers format' }, { keyword: 'person|human|athlete|model', label: 'Includes human element' }, { keyword: 'phone|app|screen|device', label: 'Shows the product' }],
    sample_answer: 'A dynamic photo of a fit young athlete mid-workout in a modern gym, smartphone strapped to forearm displaying the PulseTrack app interface with glowing heart rate data, vibrant teal and coral color accents, dramatic side lighting with lens flare, square composition with subject centered, high contrast, energetic and motivational mood, shallow depth of field, professional sports photography style.',
  },
  {
    id: 3,
    category: 'image-prompting',
    title: 'Email Banner Design',
    difficulty: 'medium',
    points: 20,
    description: 'Write a prompt for a seasonal promotional email header image.',
    prompt: 'An online course platform is running a "New Year, New Skills" January promotion with 40% off all courses. Write an AI image prompt for the email header banner (600x200px wide format) that feels festive yet professional.',
    hints: ['Wide horizontal format needs careful composition', 'Balance festive elements without being too holiday-specific', 'Leave negative space for text overlay', 'Keep it professional — this is an education brand', 'Seasonal colors that feel fresh and aspirational'],
    criteria: [{ keyword: 'wide|horizontal|banner|600|header', label: 'Addresses banner format' }, { keyword: 'new year|january|season|winter|fresh', label: 'Captures seasonal theme' }, { keyword: 'education|learn|course|skill|book|study', label: 'Relates to education' }, { keyword: 'space|text|overlay|room|minimal', label: 'Considers text overlay space' }, { keyword: 'professional|clean|modern|elegant', label: 'Maintains professional tone' }],
    sample_answer: 'A wide horizontal banner illustration, clean modern flat design style, depicting an open laptop surrounded by floating icons of books, graduation caps, and lightbulbs, subtle confetti and sparkle elements suggesting New Year celebration, color palette of navy blue, white, and gold accents, large empty space on the right side for text overlay, soft gradient background, professional yet aspirational mood, minimal and uncluttered composition.',
  },
  {
    id: 4,
    category: 'image-prompting',
    title: 'Brand Lifestyle Photography',
    difficulty: 'medium',
    points: 20,
    description: 'Create a prompt for lifestyle imagery that represents a remote work tool brand.',
    prompt: 'A remote collaboration tool called "TeamSync" needs lifestyle photography for their website and social media. Write an AI image prompt that shows authentic remote work scenarios while maintaining brand appeal.',
    hints: ['Lifestyle photos should feel natural, not staged', 'Show real work environments (home office, cafe, co-working)', 'Include technology naturally in the scene', 'Diverse representation matters', 'Warm, inviting atmosphere over cold corporate'],
    criteria: [{ keyword: 'natural|authentic|candid|real|organic', label: 'Emphasizes authenticity' }, { keyword: 'remote|home|cafe|coworking|anywhere', label: 'Shows remote work setting' }, { keyword: 'laptop|screen|device|tech|computer', label: 'Includes technology' }, { keyword: 'warm|cozy|inviting|comfort', label: 'Creates warm atmosphere' }, { keyword: 'collaboration|team|together|connect|call', label: 'Shows collaboration' }],
    sample_answer: 'A warm, candid lifestyle photograph of a smiling professional on a video call from a bright, cozy home office, natural morning light streaming through a window, laptop screen showing a team video grid, coffee cup and notebook on a wooden desk, potted plants in background, shallow depth of field, warm color temperature, authentic and relaxed mood, editorial photography style, soft natural shadows.',
  },
  {
    id: 5,
    category: 'image-prompting',
    title: 'App Store Screenshots',
    difficulty: 'medium',
    points: 20,
    description: 'Write a prompt for generating stylized app store screenshot backgrounds.',
    prompt: 'A meditation app called "Stillness" needs beautiful background visuals for their App Store screenshots. Write an AI image prompt that creates a serene, premium background that the UI mockups will be placed on top of.',
    hints: ['App Store screenshots need clean backgrounds for UI readability', 'Meditation apps favor nature, calm, and tranquility', 'Premium feel with subtle textures and gradients', 'Consider multiple color variations', 'The background should not compete with the UI overlay'],
    criteria: [{ keyword: 'calm|serene|peaceful|tranquil|zen', label: 'Evokes calmness' }, { keyword: 'background|backdrop|behind|subtle', label: 'Designed as background' }, { keyword: 'gradient|soft|blur|gentle|smooth', label: 'Uses soft visual elements' }, { keyword: 'premium|luxury|elegant|high.end|polish', label: 'Feels premium' }, { keyword: 'nature|sky|water|cloud|mountain|abstract', label: 'Uses calming imagery' }],
    sample_answer: 'An ultra-soft abstract background for mobile app screenshots, gentle gradient flowing from deep indigo at the top to soft lavender at the bottom, subtle watercolor cloud textures overlaid with ethereal light rays, tiny floating particles of golden light suggesting a meditative atmosphere, extremely clean and minimal with large smooth areas, premium and serene aesthetic, no sharp elements or busy details, 4K resolution, portrait orientation.',
  },
  {
    id: 6,
    category: 'image-prompting',
    title: 'Infographic Hero Visual',
    difficulty: 'hard',
    points: 30,
    description: 'Create a prompt for the main visual of a data-driven marketing infographic.',
    prompt: 'A fintech startup needs a central visual element for an infographic titled "The State of Digital Payments 2025". Write an AI image prompt that creates an impactful, data-themed hero visual that will anchor the infographic design.',
    hints: ['Infographic visuals should be bold and iconic', 'Data visualization elements (graphs, nodes, networks)', 'Fintech requires trust and innovation simultaneously', 'The visual needs to work at various sizes', 'Isometric or 3D elements work well for infographics'],
    criteria: [{ keyword: 'data|graph|chart|visual|node|network', label: 'Includes data visualization elements' }, { keyword: 'fintech|payment|finance|money|digital|transaction', label: 'References fintech theme' }, { keyword: '3d|isometric|dimension|render', label: 'Uses dimensional style' }, { keyword: 'bold|impactful|striking|eye.catch|hero', label: 'Creates visual impact' }, { keyword: 'modern|future|innovat|tech|digital', label: 'Conveys innovation' }],
    sample_answer: 'A striking 3D isometric illustration of a futuristic digital payment ecosystem, featuring a central glowing smartphone surrounded by interconnected nodes representing banks, wallets, and merchants, flowing data streams in neon blue and green, holographic currency symbols floating in space, dark navy background with subtle grid lines, clean vector-like rendering with metallic and glass material effects, bold and impactful composition suitable for an infographic centerpiece, modern tech aesthetic, 4K.',
  },
  {
    id: 7,
    category: 'image-prompting',
    title: 'YouTube Thumbnail',
    difficulty: 'easy',
    points: 10,
    description: 'Write a prompt for a clickable YouTube video thumbnail.',
    prompt: 'A marketing educator is publishing a video titled "5 Facebook Ad Mistakes Costing You Money". Write an AI image prompt for a YouTube thumbnail that maximizes click-through rate.',
    hints: ['YouTube thumbnails need to be readable at small sizes', 'High contrast and bold colors perform best', 'Emotional facial expressions drive clicks', 'Keep composition simple and uncluttered', 'Consider the 16:9 aspect ratio'],
    criteria: [{ keyword: 'face|expression|emotion|shock|surprise|person', label: 'Includes human expression' }, { keyword: 'bold|bright|contrast|vivid|saturate', label: 'Uses bold visuals' }, { keyword: 'simple|clean|unclutter|minimal|clear', label: 'Keeps composition simple' }, { keyword: 'thumbnail|youtube|16.9|small|click', label: 'Considers thumbnail format' }, { keyword: 'money|dollar|cost|loss|waste|facebook|ad', label: 'Relates to the topic' }],
    sample_answer: 'A bold YouTube thumbnail, professional marketer with exaggerated shocked facial expression holding their head, bright red and yellow background split diagonally, large dollar bills flying away to one side, Facebook logo subtly visible, extremely high contrast and saturation, clean uncluttered composition, 16:9 landscape format, large clear shapes readable at small sizes, dramatic studio lighting on the face, professional photography.',
  },
  {
    id: 8,
    category: 'image-prompting',
    title: 'Product Mockup Scene',
    difficulty: 'hard',
    points: 30,
    description: 'Create a detailed prompt for a multi-device product mockup scene.',
    prompt: 'An e-commerce platform called "ShopVerse" needs a hero mockup showing their platform across multiple devices (desktop, tablet, mobile) in a professional lifestyle setting. Write a detailed AI image prompt.',
    hints: ['Multi-device scenes need careful spatial arrangement', 'Consistent lighting across all devices is crucial', 'The lifestyle context should match the e-commerce sector', 'Each screen should feel active and realistic', 'Premium materials and textures elevate the scene'],
    criteria: [{ keyword: 'desktop|laptop|monitor|computer', label: 'Includes desktop device' }, { keyword: 'tablet|ipad', label: 'Includes tablet' }, { keyword: 'mobile|phone|smartphone', label: 'Includes mobile' }, { keyword: 'light|shadow|reflect|glow', label: 'Describes lighting setup' }, { keyword: 'angle|perspective|composition|arrange|layout', label: 'Specifies spatial arrangement' }, { keyword: 'e.commerce|shop|store|product|retail', label: 'Relates to e-commerce' }],
    sample_answer: 'A premium product mockup scene featuring three Apple devices arranged on a sleek marble desk: a MacBook Pro centered showing a colorful e-commerce storefront, iPad tilted at 75 degrees to the left displaying a product category page, iPhone upright in the foreground showing a mobile checkout screen, warm ambient lighting from the left with soft desk lamp glow, subtle reflections on the marble surface, minimalist desk accessories including a small plant and coffee cup, shallow depth of field, photorealistic 3D render, clean editorial photography style, 8K ultra-detailed.',
  },
  {
    id: 9,
    category: 'image-prompting',
    title: 'Brand Pattern Design',
    difficulty: 'hard',
    points: 30,
    description: 'Write a prompt for a seamless brand pattern to use across marketing materials.',
    prompt: 'A health and wellness subscription box brand called "VitalBox" needs a signature seamless pattern for packaging, social media backgrounds, and website sections. Write an AI prompt that generates this pattern.',
    hints: ['Seamless/tileable patterns need specific instructions', 'Health/wellness has specific visual language (organic, natural, fresh)', 'The pattern must work at different scales', 'Balance between decorative and not overwhelming', 'Consider how it looks when repeated'],
    criteria: [{ keyword: 'seamless|tile|tileable|repeat|pattern', label: 'Specifies seamless pattern' }, { keyword: 'health|wellness|organic|natural|vitality', label: 'Matches brand theme' }, { keyword: 'scale|size|small|versatile|adapt', label: 'Considers scalability' }, { keyword: 'color|palette|tone|hue', label: 'Defines color direction' }, { keyword: 'element|icon|shape|leaf|fruit|botanical', label: 'Describes pattern elements' }],
    sample_answer: 'A seamless tileable pattern design for a wellness brand, featuring delicate hand-drawn botanical illustrations of herbs, leaves, citrus slices, and small berries, interspersed with subtle geometric dots and thin flowing lines, soft muted color palette of sage green, dusty rose, warm cream, and touches of golden yellow on a white background, evenly distributed elements with balanced negative space, organic and fresh feeling, works at both small and large scale, flat illustration style with thin linework, vector-clean edges.',
  },
  {
    id: 10,
    category: 'image-prompting',
    title: 'Before/After Comparison',
    difficulty: 'medium',
    points: 20,
    description: 'Create a prompt for a before/after visual demonstrating a product transformation.',
    prompt: 'A website builder tool called "PageCraft" wants to show a dramatic before/after visual — "ugly website" vs "beautiful website built with PageCraft". Write an AI image prompt for this split-screen comparison.',
    hints: ['The contrast between before and after should be dramatic', 'Split-screen or side-by-side composition', 'The "before" should be recognizably bad but not offensive', 'The "after" should showcase modern web design', 'Consistent framing makes the comparison fair'],
    criteria: [{ keyword: 'before|after|comparison|split|versus|side.by.side', label: 'Establishes comparison format' }, { keyword: 'ugly|bad|old|outdated|cluttered|poor', label: 'Describes the before state' }, { keyword: 'beautiful|modern|clean|polished|stunning', label: 'Describes the after state' }, { keyword: 'website|page|web|design|layout|site', label: 'References web design' }, { keyword: 'contrast|dramatic|transform|difference', label: 'Emphasizes the transformation' }],
    sample_answer: 'A side-by-side split-screen comparison image of two website mockups on browser windows: LEFT side shows an outdated, cluttered website with mismatched fonts, garish colors, crowded layout, and pixelated images, slightly desaturated and dull lighting; RIGHT side shows the same content reimagined as a stunning modern website with clean typography, harmonious color scheme, elegant spacing, and crisp imagery, bright and vibrant lighting, a clear dividing line in the center, consistent browser chrome framing on both sides, flat design illustration style.',
  },

  // ===== CAMPAIGN STRATEGY (10) =====
  {
    id: 11,
    category: 'campaign-strategy',
    title: 'SaaS Launch Campaign',
    difficulty: 'medium',
    points: 20,
    description: 'Design a go-to-market campaign strategy for a new SaaS product launch.',
    prompt: 'You are the marketing lead for "CloudDesk", a new cloud-based virtual office platform for remote teams (priced at $12/user/month). Design a 30-day launch campaign strategy that builds awareness and drives sign-ups for a free trial.',
    hints: ['Consider pre-launch, launch day, and post-launch phases', 'Include multiple channels (social, email, content, paid)', 'Set specific goals and KPIs for each phase', 'Think about the target audience and messaging', 'Include a budget allocation strategy'],
    criteria: [{ keyword: 'phase|week|day|timeline|schedule', label: 'Defines campaign phases/timeline' }, { keyword: 'social|email|content|paid|channel|seo|blog', label: 'Uses multiple channels' }, { keyword: 'kpi|goal|metric|target|conversion|sign.up', label: 'Sets measurable goals' }, { keyword: 'audience|persona|user|customer|segment', label: 'Identifies target audience' }, { keyword: 'budget|spend|allocat|invest|cost', label: 'Addresses budget' }, { keyword: 'message|position|value|proposition|story', label: 'Defines messaging' }],
    sample_answer: 'Phase 1 (Days 1-10) Pre-Launch: Build anticipation with teaser content on LinkedIn and Twitter, launch a founding members waitlist landing page, publish 3 blog posts on remote work challenges, partner with 5 remote work influencers. Budget: 30% on paid social teasers. KPI: 2,000 waitlist signups. Phase 2 (Days 11-15) Launch Week: Product Hunt launch, press outreach, email blast to waitlist with exclusive 60-day free trial, live demo webinar, employee advocacy push. Budget: 40% on launch PR and ads. KPI: 500 free trial signups. Phase 3 (Days 16-30) Post-Launch: Retargeting campaigns, case study with beta users, email nurture sequence, blog SEO content. Budget: 30% on retargeting and content. KPI: 15% trial-to-paid conversion.',
  },
  {
    id: 12,
    category: 'campaign-strategy',
    title: 'Seasonal Sale Campaign',
    difficulty: 'easy',
    points: 10,
    description: 'Plan a Black Friday campaign for a digital product.',
    prompt: 'You manage marketing for an online learning platform that sells individual courses ($49-$199). Plan a Black Friday/Cyber Monday campaign strategy that maximizes revenue over the 5-day sale period.',
    hints: ['Black Friday campaigns start weeks before the actual day', 'Urgency and scarcity are key psychological drivers', 'Email segmentation is crucial for personalization', 'Consider tiered discounts or bundles', 'Plan for the entire BFCM week, not just one day'],
    criteria: [{ keyword: 'email|list|segment|subscriber', label: 'Uses email marketing' }, { keyword: 'discount|offer|deal|percent|price|bundle', label: 'Defines the offer' }, { keyword: 'urgency|scarcity|limit|countdown|expire', label: 'Creates urgency' }, { keyword: 'before|pre|tease|warm|early', label: 'Plans pre-event buildup' }, { keyword: 'social|ad|paid|facebook|instagram', label: 'Includes promotional channels' }],
    sample_answer: 'Week Before: Tease biggest sale ever on social media and email, send VIP early access to top 10% spenders. Black Friday: Launch 50% off all courses with 48-hour countdown timer, segment emails by interest, run Facebook/Instagram carousel ads. Saturday-Sunday: Bundle deal — buy 2 get 1 free, social proof emails. Cyber Monday: Final 60% flash sale on select courses, last chance email series, retarget all cart abandoners. Post-BFCM: Thank you email with content recommendations, upsell annual subscription.',
  },
  {
    id: 13,
    category: 'campaign-strategy',
    title: 'Referral Program Design',
    difficulty: 'medium',
    points: 20,
    description: 'Design a viral referral campaign for a mobile app.',
    prompt: 'A budgeting app "PennyWise" has 50,000 active users but growth has stalled. Design a referral campaign strategy that incentivizes existing users to invite friends and creates a viral loop.',
    hints: ['Both the referrer and referred should benefit', 'Make sharing frictionless (one-tap, unique links)', 'Gamification elements boost participation', 'Track referral metrics carefully', 'Consider tiered rewards for super-referrers'],
    criteria: [{ keyword: 'reward|incentive|benefit|bonus|credit|free', label: 'Defines incentive structure' }, { keyword: 'share|invite|refer|link|code', label: 'Explains sharing mechanism' }, { keyword: 'both|two.sided|referrer|referred|friend', label: 'Benefits both parties' }, { keyword: 'tier|level|milestone|badge|gamif', label: 'Includes gamification' }, { keyword: 'track|metric|measure|kpi|rate', label: 'Plans measurement' }],
    sample_answer: 'Referral Structure: Give $5 credit to both referrer and new user when the friend completes their first budget. Sharing: In-app share button generating unique deep links for WhatsApp, SMS, email, and social media. Gamification: Tiered rewards — 3 referrals unlocks premium for 1 month, 10 referrals earns Money Mentor badge and lifetime premium, leaderboard showing top referrers. Campaign Launch: In-app notification + email blast, push notifications after key actions. Tracking: Referral dashboard with conversion funnel, target 15% participation rate.',
  },
  {
    id: 14,
    category: 'campaign-strategy',
    title: 'Product Repositioning',
    difficulty: 'hard',
    points: 30,
    description: 'Create a strategy to reposition a struggling digital product.',
    prompt: 'A generic "to-do list" app has been losing users to competitors. Market research shows users love the simplicity but see it as "too basic". Rebrand and reposition it as a productivity tool for creative professionals. Outline the campaign strategy.',
    hints: ['Repositioning requires changing perception, not just features', 'Identify what creative professionals specifically need', 'Influencer partnerships in the creative space are powerful', 'Content marketing can establish authority in the niche', 'The transition should feel authentic, not forced'],
    criteria: [{ keyword: 'rebrand|reposition|rename|identity|brand', label: 'Addresses rebranding' }, { keyword: 'creative|designer|artist|writer|creator', label: 'Targets creative professionals' }, { keyword: 'influencer|partner|ambassador|collab', label: 'Leverages influencers' }, { keyword: 'content|blog|story|case.study|testimonial', label: 'Uses content marketing' }, { keyword: 'message|position|narrative|story|perception', label: 'Defines new positioning' }, { keyword: 'feature|workflow|template|integrat', label: 'Aligns product with audience' }],
    sample_answer: 'Phase 1 — Rebrand: Rename to "MakeFlow", new visual identity with creative-focused aesthetics. New positioning: "The task manager that thinks like a creative." Add creative-specific templates. Phase 2 — Influencer Seeding: Partner with 20 YouTubers/Instagrammers in design, writing, and music production niches. Phase 3 — Content Authority: Launch "The Creative Process" blog and podcast interviewing successful creatives. Phase 4 — Community: Create a Discord community for creative professionals. Phase 5 — Paid Campaign: Targeted ads on Behance, Dribbble, and creative YouTube channels.',
  },
  {
    id: 15,
    category: 'campaign-strategy',
    title: 'Freemium to Premium Upsell',
    difficulty: 'medium',
    points: 20,
    description: 'Design an upsell campaign to convert free users to paid subscribers.',
    prompt: 'A cloud storage service has 200,000 free users (5GB plan) but only 3% are paid subscribers ($9.99/month for 100GB). Design a campaign to increase the conversion rate to 8% within 90 days.',
    hints: ['Understand why free users have not converted', 'Show value of paid features at the right moment', 'In-app triggers are more effective than generic emails', 'Limited-time offers can accelerate decisions', 'Social proof from existing paid users helps'],
    criteria: [{ keyword: 'trigger|moment|action|behavior|usage', label: 'Uses behavioral triggers' }, { keyword: 'email|notification|in.app|message|push', label: 'Defines communication channels' }, { keyword: 'offer|discount|trial|incentive|promo', label: 'Includes conversion offer' }, { keyword: 'social.proof|testimonial|review|case', label: 'Leverages social proof' }, { keyword: 'segment|cohort|group|tier|persona', label: 'Segments user base' }, { keyword: 'metric|kpi|goal|conversion|percent|rate', label: 'Sets measurable targets' }],
    sample_answer: 'Segment users into 3 groups: Light (<1GB), Active (1-3GB), Power (>3GB). Power Users: In-app banner at 80% usage with one-click upgrade, personalized email, 50% off first 3 months. Active Users: Email series on premium features, in-app prompt when they try premium features, 14-day free trial. Light Users: Re-engagement campaign, social proof. Cross-Cutting: Annual plan discount, referral bonus. KPIs: Track upgrade rate by segment weekly.',
  },
  {
    id: 16,
    category: 'campaign-strategy',
    title: 'Influencer Marketing Plan',
    difficulty: 'easy',
    points: 10,
    description: 'Develop a micro-influencer campaign strategy for a niche digital product.',
    prompt: 'A language learning app wants to grow in the Spanish-learning market using micro-influencers (10K-50K followers). With a $5,000 monthly budget, outline the influencer marketing campaign strategy.',
    hints: ['Micro-influencers have higher engagement rates than macro', 'Authenticity matters more than reach in this space', 'Define clear deliverables for each influencer', 'Track unique referral codes/links per influencer', 'Consider long-term partnerships over one-offs'],
    criteria: [{ keyword: 'micro.influencer|creator|10k|small|niche', label: 'Targets micro-influencers' }, { keyword: 'deliverable|post|story|reel|video|content', label: 'Defines deliverables' }, { keyword: 'code|link|track|utm|referral', label: 'Tracks performance' }, { keyword: 'budget|cost|pay|compensat|rate', label: 'Addresses budget allocation' }, { keyword: 'authentic|genuine|real|honest|organic', label: 'Values authenticity' }],
    sample_answer: 'Target: 8-10 micro-influencers in language learning, travel, and Hispanic culture niches on Instagram and TikTok. Criteria: 10K-50K followers, >4% engagement rate. Compensation: $300-500 per influencer per month + free premium access. Deliverables: 2 feed posts + 4 stories per month. Each gets unique promo code. Budget: $4,000 for influencers, $1,000 for boosting top content. Track: Installs and conversions per code. Goal: 500 new installs/month.',
  },
  {
    id: 17,
    category: 'campaign-strategy',
    title: 'Product Hunt Launch',
    difficulty: 'hard',
    points: 30,
    description: 'Plan a comprehensive Product Hunt launch strategy for maximum impact.',
    prompt: 'Your AI writing assistant tool is ready for its Product Hunt launch. You want to finish in the top 3 products of the day. Plan the complete launch strategy including pre-launch, launch day, and post-launch actions.',
    hints: ['Product Hunt success depends heavily on first-hour momentum', 'Build a hunter community weeks before launch', 'The maker comment and first comment strategy matters', 'Coordinate timezone with PH daily reset (12:01 AM PT)', 'Have assets ready: video demo, screenshots, tagline'],
    criteria: [{ keyword: 'pre.launch|before|advance|prepare|week', label: 'Plans pre-launch preparation' }, { keyword: 'hunter|community|supporter|upvote|vote', label: 'Builds supporter base' }, { keyword: 'launch.day|first.hour|morning|12|midnight', label: 'Has launch day timeline' }, { keyword: 'comment|maker|first|story|engage', label: 'Plans engagement strategy' }, { keyword: 'video|demo|screenshot|asset|tagline', label: 'Prepares launch assets' }, { keyword: 'post.launch|after|follow.up|convert', label: 'Has post-launch plan' }],
    sample_answer: 'Pre-Launch (4 weeks): Build PH relationships, recruit top hunter, collect 200+ email supporters, prepare demo video and screenshots. Launch Day: Go live 12:01 AM PT, maker posts authentic first comment, email all supporters, coordinate team for 10-minute comment response time, share on all social. Hours 1-6: Respond to every comment personally, share live updates. Post-Launch: PH-exclusive deal for 48 hours, thank-you email to upvoters, lessons-learned blog post.',
  },
  {
    id: 18,
    category: 'campaign-strategy',
    title: 'Crisis Communication Plan',
    difficulty: 'hard',
    points: 30,
    description: 'Develop a crisis communication strategy for a data breach scenario.',
    prompt: 'Your SaaS platform has discovered a data breach affecting 10,000 users (email addresses and hashed passwords exposed). Design the complete crisis communication and marketing recovery strategy.',
    hints: ['Speed and transparency are critical in crisis communication', 'Legal requirements may dictate notification timelines', 'Have a clear chain of command for approvals', 'Multiple stakeholder groups need different messages', 'Recovery campaign should rebuild trust over time'],
    criteria: [{ keyword: 'immediate|first|hour|fast|quick|rapid', label: 'Acts quickly' }, { keyword: 'transparent|honest|open|clear|direct', label: 'Prioritizes transparency' }, { keyword: 'email|notification|blog|social|press', label: 'Uses multiple channels' }, { keyword: 'user|customer|stakeholder|investor|team', label: 'Addresses multiple audiences' }, { keyword: 'recover|rebuild|trust|restore|long.term', label: 'Plans recovery' }, { keyword: 'secure|fix|prevent|measure|action|step', label: 'Outlines corrective actions' }],
    sample_answer: 'Hour 0-4: Internal alert, assemble crisis team, assess scope. Hour 4-12: Direct email to affected users with transparent explanation, forced password reset. Public blog post, social media statement, notify regulators. Week 1: Daily updates, free credit monitoring, technical post-mortem, CEO video. Weeks 2-4: Enhanced security measures announced, third-party audit, "Security First" content series. Months 2-3: Trust recovery campaign with customer testimonials, security certification.',
  },
  {
    id: 19,
    category: 'campaign-strategy',
    title: 'Cross-Promotion Partnership',
    difficulty: 'easy',
    points: 10,
    description: 'Create a co-marketing campaign strategy with a complementary brand.',
    prompt: 'A project management tool and a time-tracking tool want to run a co-marketing campaign together. Both are B2B SaaS with similar sized audiences (~30K email subscribers each). Design the partnership campaign.',
    hints: ['Both brands should benefit equally', 'Find the shared value proposition for their combined audience', 'Joint content is more valuable than cross-promotion alone', 'Exclusive bundle offers drive conversions', 'Measure the value each partner brings'],
    criteria: [{ keyword: 'joint|together|co.market|partner|collab', label: 'Emphasizes collaboration' }, { keyword: 'bundle|package|deal|offer|discount', label: 'Creates a joint offer' }, { keyword: 'content|webinar|blog|guide|ebook', label: 'Plans joint content' }, { keyword: 'email|audience|subscriber|list|cross', label: 'Leverages both audiences' }, { keyword: 'equal|mutual|both|shared|balanced', label: 'Ensures balanced partnership' }],
    sample_answer: 'Joint Value Prop: "The complete productivity stack." Bundle: 30% off both tools, plus native integration. Joint Content: Co-authored ebook, joint webinar, 3 co-branded blog posts. Cross-Promotion: Email swap to both lists, co-branded landing page, social media takeover day. Measurement: Track leads per partner, bundle conversion rate. Split costs 50/50.',
  },
  {
    id: 20,
    category: 'campaign-strategy',
    title: 'Community-Led Growth',
    difficulty: 'medium',
    points: 20,
    description: 'Design a community-driven growth strategy for a developer tool.',
    prompt: 'A new open-source API testing tool wants to build a community-led growth engine. They have 500 GitHub stars and 200 Discord members. Design a 6-month strategy to reach 5,000 stars and 2,000 Discord members.',
    hints: ['Open-source growth relies on developer advocacy', 'Content that solves real problems attracts developers', 'Contributor programs create loyal advocates', 'Developer events and hackathons drive awareness', 'Documentation quality directly impacts adoption'],
    criteria: [{ keyword: 'community|discord|slack|forum|member', label: 'Builds community platform' }, { keyword: 'content|tutorial|blog|video|doc', label: 'Creates developer content' }, { keyword: 'contributor|open.source|pr|github', label: 'Encourages contributions' }, { keyword: 'event|hackathon|meetup|conference|talk', label: 'Plans developer events' }, { keyword: 'advocate|champion|ambassador|evangel', label: 'Builds advocacy program' }, { keyword: 'milestone|goal|month|phase|timeline', label: 'Sets growth milestones' }],
    sample_answer: 'Months 1-2: Polish docs, "Good First Issue" program, weekly Discord office hours, comparison guides. Goal: 1,500 stars, 500 Discord. Months 3-4: Developer blog, YouTube series, conference talks, contributor spotlights. Goal: 3,000 stars, 1,000 Discord. Months 5-6: Online hackathon, Developer Ambassador program, sponsor podcasts, integration plugins. Goal: 5,000 stars, 2,000 Discord. Ongoing: Monthly newsletter, contributor recognition, public roadmap voting.',
  },

  // ===== CONTENT PLANNING (10) =====
  {
    id: 21,
    category: 'content-planning',
    title: 'Monthly Content Calendar',
    difficulty: 'easy',
    points: 10,
    description: 'Create a one-month content calendar for a B2B SaaS brand.',
    prompt: 'Plan a complete content calendar for January for a CRM software company. Include blog posts, social media content, email newsletters, and any seasonal hooks. The goal is to generate leads for a free trial.',
    hints: ['Balance educational, promotional, and engaging content', 'New Year themes are perfect for January', 'Consistency matters — set a realistic publishing cadence', 'Each piece should have a purpose in the funnel', 'Include content formats (blog, video, carousel, etc.)'],
    criteria: [{ keyword: 'blog|article|post|write', label: 'Plans blog content' }, { keyword: 'social|linkedin|twitter|instagram', label: 'Plans social content' }, { keyword: 'email|newsletter|drip|sequence', label: 'Plans email content' }, { keyword: 'january|new.year|q1|goal|resolution', label: 'Uses seasonal themes' }, { keyword: 'lead|trial|funnel|convert|cta', label: 'Ties to lead generation' }],
    sample_answer: 'Week 1 (New Year): Blog — "5 CRM Goals Every Sales Team Should Set", Social — carousel on sales trends, daily LinkedIn tips, Email — "Start Q1 strong" newsletter with free CRM audit template. Week 2: Blog — "How to Clean Your CRM Data", Social — before/after reels, poll on CRM frustrations, Email — case study. Week 3: Blog — "Complete Guide to Sales Pipeline Management", Social — infographic, live Q&A, Email — free pipeline template. Week 4: Blog — "10 CRM Automations That Save 5 Hours/Week", Social — video demo, testimonial post, Email — free trial CTA. Cadence: 4 blogs, 20 social posts, 4 emails, 1 live event.',
  },
  {
    id: 22,
    category: 'content-planning',
    title: 'Pillar Content Strategy',
    difficulty: 'medium',
    points: 20,
    description: 'Design a pillar-cluster content strategy for SEO dominance.',
    prompt: 'An email marketing platform wants to rank #1 for "email marketing" and related terms. Design a pillar-cluster content strategy with one comprehensive pillar page and supporting cluster articles.',
    hints: ['Pillar pages are comprehensive (3,000-5,000+ words)', 'Cluster content targets long-tail keywords', 'Internal linking structure is crucial for SEO', 'Each cluster should link to pillar and vice versa', 'Cover every aspect of the topic thoroughly'],
    criteria: [{ keyword: 'pillar|comprehensive|main|hub|guide', label: 'Defines pillar page' }, { keyword: 'cluster|supporting|long.tail|sub.topic', label: 'Plans cluster content' }, { keyword: 'link|internal|connect|structure|seo', label: 'Addresses linking strategy' }, { keyword: 'keyword|search|rank|serp|traffic', label: 'Targets specific keywords' }, { keyword: 'topic|section|cover|aspect|angle', label: 'Covers topic breadth' }],
    sample_answer: 'Pillar Page: "The Complete Guide to Email Marketing" (5,000 words). 10 Clusters: 1) Best Practices, 2) Building an Email List, 3) Subject Line Guide, 4) Automation Workflows, 5) Deliverability Guide, 6) Metrics & KPIs, 7) Email vs Social Media, 8) Segmentation Strategies, 9) GDPR Compliance, 10) Templates & Examples. Linking: Each cluster links to pillar in intro and CTA, pillar links to every cluster. Update pillar quarterly.',
  },
  {
    id: 23,
    category: 'content-planning',
    title: 'Video Content Series',
    difficulty: 'medium',
    points: 20,
    description: 'Plan a YouTube video content series for a digital product brand.',
    prompt: 'A design tool (like Canva) wants to launch a YouTube channel. Plan the first 10 videos, content strategy, and publishing schedule that will build an audience of design beginners.',
    hints: ['First videos should address the most common beginner questions', 'Series/playlists encourage binge-watching', 'Search-driven titles help with discovery', 'Mix tutorial and inspirational content', 'Consistent publishing schedule builds audience habits'],
    criteria: [{ keyword: 'tutorial|how.to|guide|learn|teach|step', label: 'Plans educational content' }, { keyword: 'series|playlist|episode|sequence|order', label: 'Creates series structure' }, { keyword: 'schedule|weekly|cadence|publish|frequen', label: 'Sets publishing cadence' }, { keyword: 'beginner|start|basic|easy|intro|first', label: 'Targets beginners' }, { keyword: 'search|seo|title|discover|keyword', label: 'Optimizes for discovery' }],
    sample_answer: 'Channel: "Design Made Simple" — weekly tutorials every Tuesday. 10 Videos: 1) Design 101: 5 Principles, 2) Choosing Fonts, 3) Color Theory in 10 Minutes, 4) Create a Logo in 15 Minutes, 5) Instagram Post Design Tutorial, 6) 5 Beginner Design Mistakes, 7) Remove Backgrounds, 8) Stunning Presentations, 9) YouTube Thumbnail Design, 10) Business Card Design. Format: 8-15 min, face-to-camera + screen recording, chapters. Playlists: Design Basics, Social Media Design, Business Design. Promotion: Clips on Reels/TikTok.',
  },
  {
    id: 24,
    category: 'content-planning',
    title: 'Newsletter Growth Strategy',
    difficulty: 'easy',
    points: 10,
    description: 'Design a content strategy to grow an email newsletter from 0 to 5,000 subscribers.',
    prompt: 'You are launching a weekly newsletter about digital marketing trends called "The Marketing Minute". Plan the content strategy, growth tactics, and first 4 edition themes to go from 0 to 5,000 subscribers in 3 months.',
    hints: ['Newsletter growth requires both content quality and distribution', 'Lead magnets drive email sign-ups', 'Cross-promotion with other newsletters works', 'Social proof accelerates growth', 'The first editions set expectations'],
    criteria: [{ keyword: 'lead.magnet|free|download|resource|ebook', label: 'Uses lead magnets' }, { keyword: 'growth|tactic|strategy|promote|distribut', label: 'Plans growth tactics' }, { keyword: 'edition|issue|theme|topic|week', label: 'Outlines newsletter editions' }, { keyword: 'cross|partner|referral|collab|share', label: 'Leverages partnerships' }, { keyword: 'subscriber|signup|list|email|opt.in', label: 'Focuses on subscriber growth' }],
    sample_answer: 'Format: Weekly 5-minute read — 3 trends, 2 tools, 1 hot take. Growth: Lead magnet "2025 Digital Marketing Toolkit", cross-promote with 5 newsletters, referral program, Twitter thread strategy. First 4 Editions: #1 AI in Marketing, #2 Death of Third-Party Cookies, #3 TikTok vs Reels vs Shorts, #4 Email Marketing Proof Points. Landing Page: Social proof, clear value prop, sample preview. Goals: Month 1: 1,000, Month 2: 2,500, Month 3: 5,000.',
  },
  {
    id: 25,
    category: 'content-planning',
    title: 'Podcast Launch Plan',
    difficulty: 'hard',
    points: 30,
    description: 'Plan the complete launch strategy for a branded podcast.',
    prompt: 'A B2B cybersecurity company wants to launch a podcast called "Breach Brief" to build thought leadership. Plan the complete content strategy including format, first 8 episode topics, guest strategy, and promotion plan.',
    hints: ['B2B podcasts should balance education and entertainment', 'Consistent format creates listener expectations', 'Guest selection is a growth strategy', 'Launch with multiple episodes for binge-listening', 'Repurpose podcast content across channels'],
    criteria: [{ keyword: 'format|structure|length|segment|section', label: 'Defines podcast format' }, { keyword: 'episode|topic|title|season', label: 'Plans specific episodes' }, { keyword: 'guest|interview|expert|speaker', label: 'Has guest strategy' }, { keyword: 'launch|first|initial|premiere|debut', label: 'Plans launch approach' }, { keyword: 'promot|distribut|market|share|social', label: 'Plans promotion' }, { keyword: 'repurpose|clip|blog|social|video', label: 'Repurposes content' }],
    sample_answer: 'Format: Bi-weekly, 30-40 min. Structure: 5-min news, 20-min interview, 5-min Quick Wins. Launch: Drop first 3 episodes together. 8 Episodes: 1) Why Every Company Will Be Breached, 2) Social Engineering, 3) Zero Trust Architecture, 4) Ransomware Decisions, 5) Cloud Security Mistakes, 6) The CISO Life, 7) AI in Cybersecurity, 8) Building Security Culture. Guests: 50% customers, 30% experts, 20% adjacent fields. Promotion: LinkedIn audiograms, blog summaries, guest cross-promotion. Repurpose: Each episode → blog + 3 clips + 5 quotes + newsletter section.',
  },
  {
    id: 26,
    category: 'content-planning',
    title: 'UGC Content Strategy',
    difficulty: 'medium',
    points: 20,
    description: 'Build a user-generated content strategy for a consumer brand.',
    prompt: 'A sustainable fashion brand wants to leverage user-generated content (UGC) as the foundation of their social media strategy. Design a UGC content plan that collects, curates, and features customer content across platforms.',
    hints: ['UGC requires clear incentives for participation', 'Brand hashtags help organize and discover UGC', 'Rights management and permissions are essential', 'Mix UGC with branded content for quality balance', 'Feature real customers to build community'],
    criteria: [{ keyword: 'hashtag|tag|mention|branded', label: 'Creates branded hashtag' }, { keyword: 'incentive|reward|feature|spotlight|contest', label: 'Incentivizes participation' }, { keyword: 'permission|rights|consent|legal|approve', label: 'Addresses content rights' }, { keyword: 'curate|select|quality|moderate|review', label: 'Plans curation process' }, { keyword: 'community|customer|advocate|real|authentic', label: 'Builds community' }],
    sample_answer: 'Hashtag: #WearConscious. Incentive: Monthly Style Star contest, $100 credit, feature on main Instagram. Collection: Monitor hashtag daily, DM for permission. Content Mix: 60% UGC, 25% branded, 15% educational. Curation: Diverse representation, good lighting, product visible. Platforms: Instagram UGC feed + stories, TikTok styling videos, website gallery on product pages. Community: VIP customer group, early access to collections.',
  },
  {
    id: 27,
    category: 'content-planning',
    title: 'Content Repurposing Framework',
    difficulty: 'easy',
    points: 10,
    description: 'Create a system to repurpose one piece of content into 10+ assets.',
    prompt: 'You have a 2,000-word blog post about "Remote Work Productivity Tips". Design a repurposing framework that turns this single blog post into at least 10 different content pieces across multiple platforms.',
    hints: ['Think about different formats: text, visual, audio, video', 'Each platform has its own native format preferences', 'Not every repurposed piece needs all the original info', 'Quotes, stats, and tips can stand alone', 'Sequence the repurposing to maximize shelf life'],
    criteria: [{ keyword: 'video|reel|tiktok|youtube|short', label: 'Creates video content' }, { keyword: 'infographic|carousel|visual|image|graphic', label: 'Creates visual content' }, { keyword: 'social|linkedin|twitter|instagram|thread', label: 'Plans social posts' }, { keyword: 'email|newsletter', label: 'Includes email content' }, { keyword: '10|multiple|piece|asset|format|platform', label: 'Creates 10+ pieces' }],
    sample_answer: 'From one blog post: 1) LinkedIn article, 2) Twitter thread, 3) Instagram carousel, 4) Infographic, 5) TikTok/Reel — top 3 tips, 6) YouTube Short — animated tip, 7) Email newsletter version, 8) Pinterest pin, 9) LinkedIn poll, 10) Quote graphics x3, 11) Podcast segment, 12) SlideShare presentation. Timeline: Week 1 — blog + LinkedIn + thread, Week 2 — carousel + infographic + email, Week 3 — video + Pinterest, Week 4 — poll + quotes + podcast.',
  },
  {
    id: 28,
    category: 'content-planning',
    title: 'Content Audit & Gap Analysis',
    difficulty: 'hard',
    points: 30,
    description: 'Design a content audit framework to identify content gaps and opportunities.',
    prompt: 'A B2B marketing automation platform has 150 blog posts published over 3 years but traffic has plateaued. Design a comprehensive content audit framework that identifies what to keep, update, consolidate, or delete, and reveals content gaps.',
    hints: ['Use data (traffic, rankings, conversions) to evaluate content', 'Group content by topic clusters to find gaps', 'Some content cannibalizes other content in search', 'Outdated content can hurt domain authority', 'The audit should lead to a clear action plan'],
    criteria: [{ keyword: 'metric|traffic|ranking|performance|data|analytic', label: 'Uses data-driven evaluation' }, { keyword: 'keep|update|consolidat|delete|archive|action', label: 'Defines action categories' }, { keyword: 'gap|missing|opportunity|compete|keyword', label: 'Identifies content gaps' }, { keyword: 'cluster|topic|group|categor|theme', label: 'Groups by topic' }, { keyword: 'audit|framework|process|step|system', label: 'Creates systematic process' }, { keyword: 'cannibal|duplicate|overlap|similar|merge', label: 'Addresses content overlap' }],
    sample_answer: 'Step 1 — Data Collection: Export all URLs with GA metrics and GSC data. Step 2 — Scoring: Rate on Traffic, SEO Position, Conversion Rate, Freshness. Step 3 — Actions: KEEP (high traffic + conversions), UPDATE (good rankings but outdated), CONSOLIDATE (multiple thin posts on same topic), DELETE/REDIRECT (zero traffic 12+ months). Step 4 — Topic Clustering: Map content into clusters, identify gaps. Step 5 — Competitive Gap Analysis: Compare against top 3 competitors. Step 6 — Action Plan: Update top 20 posts, merge 15 thin posts into 5 guides, redirect 30 low-value posts, create 10 new posts.',
  },
  {
    id: 29,
    category: 'content-planning',
    title: 'Thought Leadership Program',
    difficulty: 'hard',
    points: 30,
    description: 'Design a thought leadership content program for a CEO.',
    prompt: 'The CEO of an AI startup wants to become a recognized thought leader in the "AI for healthcare" space within 12 months. Design a complete content program including platforms, content types, frequency, and ghostwriting workflow.',
    hints: ['Thought leadership is about unique perspectives, not generic advice', 'LinkedIn is the #1 platform for B2B thought leadership', 'Speaking engagements amplify written content', 'Ghostwriting workflow needs CEO input without taking too much time', 'Consistency over perfection in publishing'],
    criteria: [{ keyword: 'linkedin|twitter|platform|social|medium', label: 'Selects platforms' }, { keyword: 'unique|perspective|opinion|original|insight', label: 'Emphasizes unique voice' }, { keyword: 'frequency|weekly|monthly|schedule|cadence', label: 'Sets publishing frequency' }, { keyword: 'speak|conference|event|panel|keynote', label: 'Includes speaking' }, { keyword: 'ghost|workflow|process|draft|review|edit', label: 'Defines creation workflow' }, { keyword: 'measure|result|follower|engage|reach', label: 'Plans measurement' }],
    sample_answer: 'Platforms: LinkedIn (primary), Twitter (secondary), Medium (long-form), podcast guest appearances. Cadence: LinkedIn 3 posts/week, 1 article/month. Twitter daily + 2 threads/week. Medium monthly. Speaking: 1 conference/quarter, 1 podcast/month. Pillars: AI ethics, practical AI in hospitals, personalized medicine, CEO journey. Ghostwriting: Monthly 30-min brain dump → writer creates batch → CEO reviews 30 min → scheduled. Measurement: LinkedIn followers (20K goal), engagement rate >3%, speaking invitations, inbound press.',
  },
  {
    id: 30,
    category: 'content-planning',
    title: 'Interactive Content Strategy',
    difficulty: 'medium',
    points: 20,
    description: 'Plan a strategy using interactive content to boost engagement and capture leads.',
    prompt: 'A marketing analytics tool wants to use interactive content (quizzes, calculators, assessments) to generate leads. Design a strategy that includes 3 interactive content pieces, promotion plan, and lead nurture sequence.',
    hints: ['Interactive content has 2x engagement vs static content', 'Results pages are the best place for soft CTAs', 'Quizzes and assessments provide natural segmentation', 'The value of results should justify the email gate', 'Promote interactive content like a product, not a blog post'],
    criteria: [{ keyword: 'quiz|calculator|assessment|interactive|tool', label: 'Creates interactive content' }, { keyword: 'lead|capture|gate|email|form', label: 'Captures leads' }, { keyword: 'result|score|recommendation|personal', label: 'Delivers personalized results' }, { keyword: 'promote|share|distribut|ad|social', label: 'Plans promotion' }, { keyword: 'nurture|sequence|follow.up|email|drip', label: 'Plans lead nurture' }],
    sample_answer: 'Piece 1: "Marketing Analytics Maturity Assessment" — 12 questions, email gate for detailed PDF. Piece 2: "Marketing ROI Calculator" — input metrics, email for saved results. Piece 3: "Which Metrics Should You Track?" quiz — decision-tree, email for dashboard template. Promotion: LinkedIn ads, embed in blogs, partner newsletters. Nurture: Segment by results — Beginners get educational series, Intermediate get case studies, Advanced get demo offer. Sequence: Day 1 recap, Day 3 resource, Day 7 case study, Day 14 feature, Day 21 demo.',
  },

  // ===== FACEBOOK CAMPAIGNS (10) =====
  {
    id: 31,
    category: 'facebook-campaigns',
    title: 'Campaign Objective Selection',
    difficulty: 'easy',
    points: 10,
    description: 'Choose the right Facebook campaign objective for a given business goal.',
    prompt: 'An online course creator has just launched a new $99 course on "Digital Photography for Beginners" and wants to run Facebook ads. They want to maximize course purchases directly from the ad. Which campaign objective should they use and why? Explain the full campaign structure (Campaign > Ad Set > Ad).',
    hints: ['Facebook has 6 main campaign objectives in the new Outcome-Driven Ads', 'The objective tells Facebook algorithm what to optimize for', 'Conversion campaigns need the Facebook Pixel properly installed', 'Campaign structure follows a hierarchy', 'Consider the customer journey stage'],
    criteria: [{ keyword: 'conversion|sales|purchase', label: 'Selects correct objective (Sales/Conversions)' }, { keyword: 'pixel|tracking|event', label: 'Mentions pixel/tracking' }, { keyword: 'campaign|ad.set|ad|structure|level', label: 'Explains campaign structure' }, { keyword: 'optimize|algorithm|delivery', label: 'Understands optimization' }, { keyword: 'audience|target|who', label: 'Addresses targeting' }],
    sample_answer: 'Use the Sales (Conversions) objective, optimizing for the Purchase event. Campaign Level: Sales objective, CBO at $50/day. Ad Set Level: Target photography enthusiasts, ages 25-55, Advantage+ audience, Pixel Purchase event, 7-day click attribution. Ad Level: 3-4 variations (video testimonial, carousel, single image). Pixel: Must fire Purchase event on thank-you page with $99 value.',
  },
  {
    id: 32,
    category: 'facebook-campaigns',
    title: 'Audience Targeting Strategy',
    difficulty: 'medium',
    points: 20,
    description: 'Build a layered Facebook audience targeting strategy.',
    prompt: 'A meal prep delivery service (healthy, pre-made meals, $12/meal) needs a Facebook targeting strategy. Build three audience layers: cold (prospecting), warm (retargeting), and hot (conversion). Define each audience with specific targeting parameters.',
    hints: ['Cold audiences are people who have never heard of you', 'Warm audiences have interacted but not purchased', 'Hot audiences have shown purchase intent', 'Lookalike audiences are powerful for cold prospecting', 'Exclusions are as important as inclusions'],
    criteria: [{ keyword: 'cold|prospect|top.funnel|awareness|new', label: 'Defines cold audience' }, { keyword: 'warm|retarget|middle|engaged|visited', label: 'Defines warm audience' }, { keyword: 'hot|convert|bottom|cart|intent|purchase', label: 'Defines hot audience' }, { keyword: 'lookalike|similar|lal|percent', label: 'Uses lookalike audiences' }, { keyword: 'exclude|exclusion|remove|suppress', label: 'Sets up exclusions' }, { keyword: 'interest|behavior|demographic|age', label: 'Specifies targeting details' }],
    sample_answer: 'COLD: 1% lookalike of customers, interest-based (meal prep, healthy eating, fitness, ages 25-45). Exclude warm/hot + customers. Budget: 60%. WARM: Website visitors 30 days, social engagers 60 days, video viewers 50%+, cart abandoners 14 days. Exclude customers. Budget: 25%. HOT: Cart abandoners 3 days, checkout initiators, past customers for repeat orders. Budget: 15%. Key: Exclude current subscribers from all acquisition campaigns.',
  },
  {
    id: 33,
    category: 'facebook-campaigns',
    title: 'Ad Creative Strategy',
    difficulty: 'easy',
    points: 10,
    description: 'Design Facebook ad creatives that drive conversions.',
    prompt: 'Write 3 different Facebook ad variations (primary text, headline, description, and creative concept) for a $29/month budgeting app targeting young professionals aged 22-30 who are struggling with saving money.',
    hints: ['Each ad should test a different angle/hook', 'Primary text can be long or short — test both', 'Headlines should be benefit-driven, not feature-driven', 'Video ads typically outperform static on Facebook', 'Social proof and numbers build credibility'],
    criteria: [{ keyword: 'primary.text|copy|body|text', label: 'Writes ad copy' }, { keyword: 'headline|hook|title', label: 'Creates headlines' }, { keyword: 'video|image|carousel|creative|visual', label: 'Describes creative concept' }, { keyword: 'three|3|variation|version|different', label: 'Provides 3 variations' }, { keyword: 'save|money|budget|finance|spend', label: 'Addresses the pain point' }],
    sample_answer: 'Ad 1 — Pain Point: Text: "I used to check my bank account and hope for the best. Then I saved $340 in my first month." Headline: "Stop Guessing. Start Saving." Creative: 15-sec savings milestone notification video. Ad 2 — Social Proof: Text: "50,000 millennials save $4,200/year average. Setup takes 3 minutes." Headline: "The Budgeting App Your Friends Use." Creative: Carousel of user testimonials. Ad 3 — FOMO: Text: "Rent due, dinner invite, car insurance. Sound familiar? There\'s a way." Headline: "Financial Anxiety? There\'s an App for That." Creative: UGC-style selfie video.',
  },
  {
    id: 34,
    category: 'facebook-campaigns',
    title: 'Budget & Bidding Strategy',
    difficulty: 'medium',
    points: 20,
    description: 'Develop an optimal budget allocation and bidding strategy.',
    prompt: 'You have a $3,000/month Facebook ad budget for an e-commerce store selling premium headphones ($149-$299). Design the complete budget allocation across campaign types, bidding strategy, and scaling plan.',
    hints: ['Split budget between prospecting and retargeting', 'CBO vs Ad Set budgets', 'Different bid strategies suit different goals', 'Scaling should be gradual (20% increments)', 'Allow for testing budget separate from scaling budget'],
    criteria: [{ keyword: 'budget|allocat|spend|dollar|percent', label: 'Allocates budget clearly' }, { keyword: 'bid|cost.cap|roas|lowest.cost|target', label: 'Defines bidding strategy' }, { keyword: 'scale|increase|grow|expand|ramp', label: 'Plans scaling approach' }, { keyword: 'test|experiment|variation|creative', label: 'Allocates testing budget' }, { keyword: 'retarget|prospect|funnel|cold|warm', label: 'Splits by funnel stage' }],
    sample_answer: 'Split: Prospecting $1,500 (50%), Retargeting $900 (30%), Testing $600 (20%). Prospecting: CBO, 3 ad sets (LAL, interest, broad). Bid: Lowest Cost then Cost Cap at target CPA $30. Retargeting: Ad Set budgets — $450 visitors 7-30d, $300 cart abandoners, $150 past purchasers. Testing: 4 new creatives/week at $150 each, kill underperformers, graduate winners. Scaling: When ROAS >3x for 5+ days, increase 20% every 3 days.',
  },
  {
    id: 35,
    category: 'facebook-campaigns',
    title: 'Retargeting Funnel',
    difficulty: 'medium',
    points: 20,
    description: 'Build a complete Facebook retargeting funnel with specific ad messaging.',
    prompt: 'An online furniture store gets 100,000 monthly website visitors but only a 1.2% conversion rate. Build a multi-stage retargeting funnel on Facebook with specific ad messaging for each stage to improve conversions.',
    hints: ['Different retargeting windows indicate different intent levels', 'Match ad messaging to where the user dropped off', 'Dynamic product ads show people what they viewed', 'Frequency capping prevents ad fatigue', 'Each stage should push users to the next'],
    criteria: [{ keyword: 'stage|level|funnel|step|sequence', label: 'Creates multi-stage funnel' }, { keyword: 'day|window|timeframe|period|duration', label: 'Sets retargeting windows' }, { keyword: 'message|copy|ad|creative|text', label: 'Tailors messaging per stage' }, { keyword: 'dynamic|catalog|product|dpa|viewed', label: 'Uses dynamic product ads' }, { keyword: 'frequency|cap|fatigue|limit', label: 'Manages ad frequency' }],
    sample_answer: 'Stage 1 — Browsers (1-7d): Dynamic Product Ads of viewed items. "Still thinking about this?" Free shipping offer. Cap: 2x/day. Stage 2 — Engagers (1-14d, 3+ products): Best sellers carousel + reviews. "Join 10,000+ happy homes." 10% off. Cap: 1.5x/day. Stage 3 — Cart Abandoners (1-7d): Dynamic cart items with urgency. "Your cart is waiting!" Free shipping + 10%, 48hr expiry. Cap: 3x/day. Stage 4 — Checkout Abandoners (1-3d): Single product, "Reserved for 24 hours." Extra 5% off. Stage 5 — Past Purchasers (30-90d): Cross-sell complementary items. Exclude purchasers <30d from all retargeting.',
  },
  {
    id: 36,
    category: 'facebook-campaigns',
    title: 'A/B Testing Framework',
    difficulty: 'easy',
    points: 10,
    description: 'Design a systematic A/B testing plan for Facebook ads.',
    prompt: 'A subscription box company is spending $2,000/month on Facebook ads but does not know what works. Design a 4-week A/B testing framework that systematically tests creative, copy, audience, and placement variables.',
    hints: ['Only test one variable at a time for clean results', 'Statistical significance requires enough data', 'Start with the highest-impact variable first', 'Document everything in a testing log', 'Apply learnings from each week to the next'],
    criteria: [{ keyword: 'week|phase|order|sequence|schedule', label: 'Creates testing timeline' }, { keyword: 'one|single|variable|isolat|control', label: 'Tests one variable at a time' }, { keyword: 'creative|image|video|visual', label: 'Tests creative elements' }, { keyword: 'copy|headline|text|hook', label: 'Tests copy elements' }, { keyword: 'audience|target|placement|platform', label: 'Tests targeting/placement' }, { keyword: 'winner|result|significan|data|metric', label: 'Defines success criteria' }],
    sample_answer: 'Week 1 — Creative Format: Video vs Carousel vs Static. Same copy, same audience, $500 split. Metric: CTR and CPA. Min 1,000 impressions each. Week 2 — Copy/Hook: Use winning format. Test Pain Point vs Social Proof vs Curiosity hooks. $500 split. Metric: CTR and conversion rate. Week 3 — Audience: Winning creative + copy. Test LAL 1% vs Interest-based vs Advantage+ broad. $500 split. Metric: CPA and ROAS. Week 4 — Placement: All winners. Test Auto vs Feed-only vs Reels+Stories. $500 split. Rules: 7-day tests, 50 conversions minimum, document in spreadsheet.',
  },
  {
    id: 37,
    category: 'facebook-campaigns',
    title: 'Lookalike Audience Strategy',
    difficulty: 'hard',
    points: 30,
    description: 'Create an advanced lookalike audience strategy using multiple seed sources.',
    prompt: 'A high-end skincare brand (average order $85) has customer data including purchase history, email lists, and website analytics. Design an advanced lookalike audience strategy with multiple seed audiences, percentage tiers, and testing methodology.',
    hints: ['Quality of seed audience directly impacts lookalike quality', 'Different seed sources create different lookalike behaviors', 'Smaller percentages (1%) are more precise', 'Layer lookalikes with interest targeting', 'Value-based lookalikes optimize for high-value customers'],
    criteria: [{ keyword: 'seed|source|custom.audience|list|data', label: 'Defines seed audiences' }, { keyword: 'percent|1%|2%|3%|5%|tier|size', label: 'Uses percentage tiers' }, { keyword: 'value|ltv|high.value|purchase|revenue', label: 'Leverages value data' }, { keyword: 'test|compare|measure|perform|layer', label: 'Plans testing approach' }, { keyword: 'email|pixel|event|website|customer', label: 'Uses multiple data sources' }, { keyword: 'exclude|overlap|separate|deduplicate', label: 'Manages audience overlap' }],
    sample_answer: 'Seeds: S1) Top 25% by LTV, S2) All purchasers 180d, S3) Repeat purchasers 2+, S4) Engaged email subscribers >30% open, S5) High-intent visitors 3+ products 30d. Tiers: 1%, 2-3%, 4-5% from each seed. Priority LALs: S1 1% (highest value), S3 1% (repeat behavior), S2 1% (broad). Value-Based: Upload customer list with LTV data. Testing: Weeks 1-2 test top 3 LALs at 1%, Weeks 3-4 test winning seed at 1% vs 3% vs 5%. Layer best LAL with skincare interests. Exclusions: Exclude customers, deduplicate LALs across ad sets. Refresh monthly.',
  },
  {
    id: 38,
    category: 'facebook-campaigns',
    title: 'Facebook Pixel Strategy',
    difficulty: 'hard',
    points: 30,
    description: 'Design a comprehensive Facebook Pixel and Conversions API implementation strategy.',
    prompt: 'A multi-product e-commerce store is setting up Facebook tracking for the first time. Design the complete pixel strategy including standard events, custom events, Conversions API setup, and how this data feeds into campaign optimization.',
    hints: ['Standard events have pre-defined names Facebook recognizes', 'Custom events can track unique business actions', 'Conversions API complements browser pixel', 'iOS 14+ privacy changes make CAPI essential', 'Event parameters provide rich data'],
    criteria: [{ keyword: 'standard.event|pageview|viewcontent|addtocart|purchase', label: 'Implements standard events' }, { keyword: 'custom.event|custom|specific|unique', label: 'Creates custom events' }, { keyword: 'capi|server.side|conversion.api|api', label: 'Implements Conversions API' }, { keyword: 'ios|privacy|cookie|tracking|opt', label: 'Addresses privacy changes' }, { keyword: 'parameter|value|content|currency|data', label: 'Passes event parameters' }, { keyword: 'optimize|campaign|audience|retarget|feed', label: 'Connects to campaign optimization' }],
    sample_answer: 'Standard Events: PageView (all pages), ViewContent (products — content_id, value), AddToCart (cart button — product data), InitiateCheckout (checkout — cart value), Purchase (confirmation — transaction value, content_ids). Custom Events: ProductQuickView, SizeSelected, WishlistAdd, ReviewRead. CAPI: Server-side via Shopify native integration, browser pixel as backup, deduplicate with event_id. Addresses iOS 14 ATT opt-outs. Parameters: All events pass content_type, content_ids, value, currency. Campaign Use: Purchase for Sales, ViewContent for Awareness, AddToCart for mid-funnel. Custom Audiences from events for retargeting. Prioritize Purchase #1 in Aggregated Events Measurement.',
  },
  {
    id: 39,
    category: 'facebook-campaigns',
    title: 'Lead Generation Campaign',
    difficulty: 'medium',
    points: 20,
    description: 'Design a Facebook lead generation campaign using Lead Forms.',
    prompt: 'A B2B software company selling HR management tools ($500/month) wants to use Facebook Lead Ads to generate demo requests. Design the complete lead generation campaign including form design, ad creative, follow-up sequence, and qualification criteria.',
    hints: ['B2B on Facebook works but requires careful targeting', 'Lead form friction impacts both quantity and quality', 'Instant follow-up dramatically improves conversion', 'Pre-filled fields make completion easy but may lower quality', 'CRM integration is essential'],
    criteria: [{ keyword: 'form|field|question|input|lead.form', label: 'Designs the lead form' }, { keyword: 'follow.up|response|email|call|sequence|crm', label: 'Plans follow-up process' }, { keyword: 'qualify|score|criteria|fit|mql|sql', label: 'Defines qualification' }, { keyword: 'target|audience|b2b|job.title|industry', label: 'Targets B2B audience' }, { keyword: 'creative|ad|copy|hook|offer', label: 'Creates ad content' }],
    sample_answer: 'Targeting: Job titles (HR Director, VP People, CHRO), company size 50-500, industries (Tech, Professional Services). Form: Higher Intent type. Fields: Name (pre-filled), Work Email (typed — quality filter), Company Name, Company Size (dropdown), Biggest HR Challenge (dropdown). CTA: "Request Free Demo." Thank You: Calendar link. Ad: 60-sec demo video. Copy: "HR teams save 15 hours/week." Follow-Up: Instant email with booking link (Zapier to CRM), SDR calls at 2 hours, sequence at Day 1/3/7. Qualification: MQL = 50+ employees. SQL = booked demo. Disqualify: personal emails, <10 employees.',
  },
  {
    id: 40,
    category: 'facebook-campaigns',
    title: 'Campaign Performance Diagnosis',
    difficulty: 'hard',
    points: 30,
    description: 'Diagnose and fix underperforming Facebook ad campaigns using metrics.',
    prompt: 'A Facebook campaign has these metrics after 14 days: $1,500 spent, 150,000 impressions, 1,200 clicks, 15 purchases, CTR 0.8%, CPC $1.25, CPM $10, CPA $100, ROAS 1.5x (product price $100). The target CPA is $40 and target ROAS is 3x. Diagnose the problems and provide a fix plan.',
    hints: ['Work through the funnel — impressions → clicks → landing page → conversion', 'CTR benchmarks: 1-2% for cold, 3-5% for retargeting', 'High CPC with low CTR = creative problem', 'High CTR with low conversion = landing page problem', 'CPA = CPM / (CTR x CVR)'],
    criteria: [{ keyword: 'ctr|click.through|creative|ad|hook', label: 'Diagnoses CTR issue' }, { keyword: 'landing|page|conversion.rate|website|cvr', label: 'Analyzes conversion rate' }, { keyword: 'audience|target|reach|frequen|fatigue', label: 'Evaluates audience' }, { keyword: 'fix|improve|optimize|action|recommend', label: 'Provides actionable fixes' }, { keyword: 'metric|data|number|benchmark|calculate', label: 'Uses data analysis' }, { keyword: 'funnel|leak|drop|stage|where', label: 'Identifies funnel leaks' }],
    sample_answer: 'Diagnosis: CTR 0.8% below 1-2% benchmark = weak creative. Landing page CVR: 15/1,200 = 1.25% below 2-3% benchmark = landing page problem. Frequency ~3 is acceptable. Two problems: creative AND landing page. Fix Creative (goal CTR 1.5%+): 3 new variations — UGC video, product demo, testimonial. New hooks in first 3 seconds. Benefit-focused headline. Fix Landing Page (goal CVR 3%+): Social proof above fold, simplify checkout, trust badges, money-back guarantee, price anchoring. Fix Audience: Narrow to 1% LAL of purchasers. Reduce budget to $50/day while testing, scale when CPA hits $50. Impact: CTR 1.5% + CVR 3% → CPA ~$28, ROAS ~3.6x.',
  },

  // ===== TARGET AUDIENCE (10) =====
  {
    id: 41,
    category: 'target-audience',
    title: 'Buyer Persona Creation',
    difficulty: 'easy',
    points: 10,
    description: 'Create a detailed buyer persona for a digital product.',
    prompt: 'Create a detailed buyer persona for a $49/month AI writing assistant tool designed for content marketers. Include demographics, psychographics, pain points, goals, and media consumption habits.',
    hints: ['A buyer persona should feel like a real person', 'Include both demographic and psychographic details', 'Pain points should connect directly to what the product solves', 'Media habits inform where to reach them', 'Include objections they might have'],
    criteria: [{ keyword: 'demographic|age|gender|income|location|education', label: 'Includes demographics' }, { keyword: 'psychographic|value|belief|motivation|lifestyle', label: 'Includes psychographics' }, { keyword: 'pain|challenge|problem|struggle|frustrat', label: 'Identifies pain points' }, { keyword: 'goal|aspir|want|achieve|objective', label: 'Defines goals' }, { keyword: 'media|channel|platform|read|watch|listen', label: 'Maps media consumption' }],
    sample_answer: 'Persona: "Marketing Maya" — 28-35, based in US, Bachelor/Master in Marketing, $55K-$80K, Content Marketing Manager at B2B SaaS (50-200 employees). Values efficiency and quality, early adopter. Pain Points: Expected to produce 15+ posts/month but only has time for 8, writer\'s block, SEO overwhelm. Goals: Promotion to Head of Content, build content engine, maintain quality at scale. Media: LinkedIn daily, HubSpot/CMI blogs, marketing podcasts, Superpath Slack community. Objections: "Will AI sound generic?", "Is $49/month worth it?"',
  },
  {
    id: 42,
    category: 'target-audience',
    title: 'Market Segmentation',
    difficulty: 'medium',
    points: 20,
    description: 'Segment the market for a digital product into distinct audience groups.',
    prompt: 'A new all-in-one social media scheduling and analytics tool is entering the market at $29/month. Identify and define 4 distinct market segments, rank them by priority, and explain why one should be the primary target.',
    hints: ['Segments should be meaningfully different', 'Consider: size, accessibility, willingness to pay, competition', 'The best segment is not always the biggest', 'Think about both B2B and B2C use cases', 'Each segment has different messaging needs'],
    criteria: [{ keyword: 'segment|group|category|market|type', label: 'Defines distinct segments' }, { keyword: 'four|4|multiple', label: 'Identifies 4 segments' }, { keyword: 'priority|rank|primary|first|focus', label: 'Ranks segments' }, { keyword: 'size|potential|revenue|tam|market', label: 'Evaluates segment potential' }, { keyword: 'why|reason|because|rationale|justif', label: 'Justifies primary choice' }, { keyword: 'message|position|value|speak|appeal', label: 'Tailors messaging' }],
    sample_answer: 'Segment 1 — Freelance Social Media Managers (PRIMARY): Managing 3-8 client accounts, $3K-8K/month, needs multi-account management. ~500K in US. Why Primary: Highest willingness to pay ($29 is invoiceable), daily use, strong word-of-mouth. Segment 2 — Small Business Owners: 1-10 employees, manage own social, need simplicity. 2M+ in US. Price sensitive. Segment 3 — Marketing Teams at Mid-Size Companies: 2-5 person teams, need collaboration, face Hootsuite/Buffer competition. Segment 4 — Content Creators: 10K-100K followers, need analytics for sponsors. Priority: 1) Freelancers, 2) Small Businesses, 3) Creators, 4) Marketing Teams.',
  },
  {
    id: 43,
    category: 'target-audience',
    title: 'Customer Journey Mapping',
    difficulty: 'medium',
    points: 20,
    description: 'Map the complete customer journey for a digital product purchase.',
    prompt: 'Map the complete customer journey from awareness to purchase and beyond for someone buying a $199/year premium productivity app. Include all touchpoints, emotions, and actions at each stage.',
    hints: ['Stages: Awareness, Consideration, Decision, Onboarding, Retention, Advocacy', 'Each stage has different emotions and needs', 'Identify the touchpoints at each stage', 'Note the "moments of truth"', 'Include post-purchase stages'],
    criteria: [{ keyword: 'aware|discover|find|first|learn', label: 'Maps awareness stage' }, { keyword: 'consider|compare|evaluate|research|review', label: 'Maps consideration stage' }, { keyword: 'decide|purchase|buy|convert|pay', label: 'Maps decision stage' }, { keyword: 'onboard|start|setup|first.use|welcome', label: 'Maps onboarding stage' }, { keyword: 'retain|renew|loyal|repeat|advocate', label: 'Maps retention/advocacy' }, { keyword: 'emotion|feel|think|pain|delight|frustrat', label: 'Captures emotions' }],
    sample_answer: 'AWARENESS: Trigger — overwhelmed managing multiple apps. Touchpoints: YouTube review, friend mention, Google search. Emotion: Frustrated, hopeful. CONSIDERATION: Visits website, reads features, watches demo, checks reviews, joins free trial. Emotion: Curious, cautious. Moment of Truth: First 10 minutes in app. DECISION: Trial experience, email nurture (day 1/3/7/12), upgrade prompt, pricing page. Emotion: Evaluating ROI. ONBOARDING: Welcome emails, in-app tutorial, first workflow. Emotion: Excited but anxious. Moment of Truth: First productive week. RETENTION (Month 2-12): Feature updates, unused feature tips, annual review. ADVOCACY: NPS survey, referral program, review request.',
  },
  {
    id: 44,
    category: 'target-audience',
    title: 'Competitive Audience Analysis',
    difficulty: 'hard',
    points: 30,
    description: 'Analyze competitor audiences to find underserved segments.',
    prompt: 'You are launching a new project management tool. Your main competitors are Asana (enterprise), Trello (simple/visual), and Monday.com (mid-market). Analyze each competitor\'s primary audience and identify an underserved segment you can win.',
    hints: ['Study competitor messaging to understand who they target', 'Look for gaps between competitor audiences', 'Underserved does not mean non-existent', 'Consider audience frustrations with current solutions', 'Your positioning should address the underserved need'],
    criteria: [{ keyword: 'asana|trello|monday|competitor', label: 'Analyzes specific competitors' }, { keyword: 'audience|user|customer|segment|who', label: 'Identifies competitor audiences' }, { keyword: 'gap|underserved|missing|unmet|overlook', label: 'Finds underserved segment' }, { keyword: 'position|differenti|unique|niche|angle', label: 'Defines positioning' }, { keyword: 'frustrat|pain|problem|complain|limit', label: 'Identifies audience frustrations' }, { keyword: 'win|capture|target|focus|strategy', label: 'Plans how to win segment' }],
    sample_answer: 'Asana: Enterprise teams 100+, project managers. Frustration: Steep learning curve, expensive. Trello: Individuals/small teams wanting visual simplicity. Frustration: Lacks depth, no reporting. Monday.com: Mid-market 20-500, operations/marketing teams. Frustration: Expensive with add-ons, feature bloat. UNDERSERVED: Creative agencies (5-30 people). Why: Asana too complex, Trello too simple for client projects, Monday too expensive. They need: Client-facing views, time tracking, visual interface, creative templates, flat pricing. Positioning: "Project management for creative teams." Win: Partner with design communities, sponsor creative conferences, agency-specific templates, flat pricing.',
  },
  {
    id: 45,
    category: 'target-audience',
    title: 'Audience Research Methods',
    difficulty: 'easy',
    points: 10,
    description: 'Design an audience research plan using free and low-cost methods.',
    prompt: 'You are launching a new digital product (an online course platform for cooking enthusiasts) and have zero customer data. Design a research plan using free or low-cost methods to understand your target audience within 2 weeks.',
    hints: ['Social listening is free and rich with insights', 'Reddit, Facebook Groups, and forums are goldmines', 'Surveys need distribution strategy', 'Competitor reviews reveal love/hate', 'Google Trends and keyword tools show demand'],
    criteria: [{ keyword: 'survey|questionnaire|poll|ask|interview', label: 'Plans primary research' }, { keyword: 'reddit|facebook.group|forum|communit|social', label: 'Uses social listening' }, { keyword: 'review|competitor|amazon|g2|app.store', label: 'Analyzes competitor reviews' }, { keyword: 'google|trend|keyword|search|seo', label: 'Uses search data' }, { keyword: 'free|low.cost|budget|cheap|no.cost', label: 'Keeps methods affordable' }],
    sample_answer: 'Week 1 — Discovery: Day 1-2: Join 10 cooking Facebook Groups, read last 50 posts each, note themes. Browse r/cooking, r/MealPrepSunday. Day 3-4: Read 100+ reviews of MasterClass, Skillshare, Udemy cooking courses. Document praised features and complaints. Day 5: Google Trends for "cooking class online", Ubersuggest for keywords. Week 2 — Validation: Day 6-7: Google Forms survey, share in Facebook Groups with permission. Day 8-10: 5 phone interviews ($10 Amazon gift cards). Day 11-14: Synthesize into audience profile, top 5 pain points, pricing sweet spot. Total cost: $50.',
  },
  {
    id: 46,
    category: 'target-audience',
    title: 'Audience Messaging Matrix',
    difficulty: 'medium',
    points: 20,
    description: 'Create a messaging matrix that maps different messages to different audience segments.',
    prompt: 'A cloud-based accounting software is marketed to three segments: freelancers, small business owners, and accountants/bookkeepers. Create a messaging matrix with unique value propositions, pain points addressed, key messages, and CTAs for each segment.',
    hints: ['Same product, different angles for different people', 'Pain points vary dramatically between segments', 'The language/jargon each segment uses is different', 'CTAs should match the decision-making style', 'Benefits matter more than features'],
    criteria: [{ keyword: 'freelancer|solo|independent|self.employ', label: 'Messages for freelancers' }, { keyword: 'small.business|owner|smb|company|employ', label: 'Messages for small businesses' }, { keyword: 'accountant|bookkeeper|cpa|financial', label: 'Messages for accountants' }, { keyword: 'value.prop|benefit|promise|solve', label: 'Defines value props per segment' }, { keyword: 'cta|action|next.step|sign.up|demo|try', label: 'Creates tailored CTAs' }, { keyword: 'pain|problem|challenge|need|frustrat', label: 'Maps pain points' }],
    sample_answer: 'FREELANCERS — Pain: Taxes confusing, too much time invoicing. Value Prop: "15 minutes a month on books, not 15 hours." Messages: Auto expense tracking, one-click invoicing, tax-ready reports. Tone: Friendly, no jargon. CTA: "Start Free — No Credit Card." SMALL BUSINESS — Pain: Outgrowing spreadsheets, need payroll, want financial visibility. Value Prop: "See finances clearly, grow confidently." Messages: Real-time dashboard, automated payroll, scale to 50 employees. Tone: Professional, growth-focused. CTA: "Book a Free Demo." ACCOUNTANTS — Pain: Multiple client chaos, tedious data entry. Value Prop: "All clients in one place, zero manual entry." Messages: Multi-client dashboard, 95% auto-categorization, client portal. Tone: Technical, efficiency-focused. CTA: "Start Partner Account — 3 Clients Free."',
  },
  {
    id: 47,
    category: 'target-audience',
    title: 'TAM SAM SOM Analysis',
    difficulty: 'hard',
    points: 30,
    description: 'Calculate Total Addressable Market, Serviceable Market, and Obtainable Market.',
    prompt: 'A new AI-powered resume builder targeting job seekers is launching at $15/month. Calculate and explain the TAM, SAM, and SOM with reasoning and data assumptions. Then explain how this analysis informs the marketing strategy.',
    hints: ['TAM = total market if 100% share', 'SAM = portion you can actually serve', 'SOM = realistic 1-2 year capture', 'Use both top-down and bottom-up approaches', 'This shapes budget and channel decisions'],
    criteria: [{ keyword: 'tam|total.addressable|total.market', label: 'Calculates TAM' }, { keyword: 'sam|serviceable|addressable|available', label: 'Calculates SAM' }, { keyword: 'som|obtainable|share|realistic|capture', label: 'Calculates SOM' }, { keyword: 'number|million|billion|calculate|estimate', label: 'Provides specific numbers' }, { keyword: 'assumption|data|source|estimate|based', label: 'States assumptions' }, { keyword: 'strategy|inform|market|implication|budget', label: 'Connects to marketing strategy' }],
    sample_answer: 'TAM: ~160M global active job seekers × $180/year = $28.8B. SAM: English-speaking, US/UK/CA/AU, white-collar, 22-55, AI-comfortable. ~25M people. SAM = $4.5B. SOM (Year 1-2): 0.1-0.3% of SAM = 25,000-75,000 subscribers. SOM = ~$9M ARR at midpoint. Strategy Implications: TAM shows massive opportunity. SAM focus means US/UK-first via Google Ads + LinkedIn. SOM of 50K subscribers needs ~500K trials (10% conversion), requiring ~5M reach through SEO ("resume tips" 2M+ monthly searches), LinkedIn ads, job board partnerships, university career centers.',
  },
  {
    id: 48,
    category: 'target-audience',
    title: 'Behavioral Targeting Strategy',
    difficulty: 'medium',
    points: 20,
    description: 'Design a behavioral targeting strategy based on user actions.',
    prompt: 'A project management SaaS has identified these user behaviors in their free trial: A) 3+ projects in first week, B) Invite team members, C) Only view dashboard, D) Use integrations. Design a targeted marketing strategy for each behavioral segment.',
    hints: ['User behavior reveals intent and readiness', 'High-activity users need less convincing', 'Low-activity users need re-engagement first', 'Each behavior needs different messaging', 'Timing matters as much as content'],
    criteria: [{ keyword: 'behavio|action|activity|signal|trigger', label: 'Uses behavioral data' }, { keyword: 'segment|group|cohort|type|cluster', label: 'Creates distinct segments' }, { keyword: 'message|email|notification|content|copy', label: 'Tailors messaging per segment' }, { keyword: 'convert|upgrade|pay|subscribe|purchase', label: 'Drives conversion' }, { keyword: 'timing|when|day|trigger|automat', label: 'Plans message timing' }],
    sample_answer: 'Segment A — Power Users (3+ projects): Fast-track to upgrade. Day 3: Email on premium features. Day 5: In-app "unlock your potential" message. Day 10: Personal CS walkthrough offer. Segment B — Team Champions (invited members): Leverage network effect. Day 2: Team workflow setup email. Day 7: Collaborative features showcase. Day 10: Team discount (15% for 5+ seats). Segment C — Window Shoppers (dashboard only): Activate them. Day 1: Quickstart video. Day 3: Pre-built template offer. Day 5: Guided in-app tour. Day 7: 10-minute setup call offer. If no action by Day 10: Survey. Segment D — Integration Users: Show depth. Day 3: Automation recipes. Day 7: API + advanced integrations (Pro). Day 10: Unlimited integrations upgrade pitch.',
  },
  {
    id: 49,
    category: 'target-audience',
    title: 'Lookalike Audience Modeling',
    difficulty: 'hard',
    points: 30,
    description: 'Design a data-driven strategy to find your best potential customers.',
    prompt: 'An e-learning platform has data on their best customers: 85% are 28-42, predominantly in tech and marketing roles, 70% found via Google search, average LTV is $450, and they enroll in 3+ courses. Design a strategy to find and reach more people like them across all digital channels.',
    hints: ['Existing data is the foundation', 'Different channels have different audience tools', 'Intent signals are powerful indicators', 'Combine demographic, behavioral, and contextual targeting', 'Test which signals predict conversion'],
    criteria: [{ keyword: 'data|analytic|customer|insight|pattern', label: 'Leverages customer data' }, { keyword: 'lookalike|similar|model|match|clone', label: 'Creates lookalike strategy' }, { keyword: 'google|search|seo|sem|intent', label: 'Uses search channels' }, { keyword: 'facebook|linkedin|social|display', label: 'Uses social/display channels' }, { keyword: 'multi.channel|cross.channel|omni|integrated', label: 'Spans multiple channels' }, { keyword: 'test|measure|optimize|refine|iterate', label: 'Plans testing and optimization' }],
    sample_answer: 'Data Foundation: Export top 20% by LTV as seed list. Google Ads: Target keywords that drove 70% of best customers, Similar Audiences from converters, bid higher on 28-42 tech/marketing demographics. SEO: Content targeting exact acquisition queries. Facebook: 1% LAL from seed list, layer with tech/marketing interests, value-based LAL with LTV data. LinkedIn: Target Marketing Manager, Data Analyst, Product Manager titles, mid-level seniority, 50+ company size. Programmatic: DMP segments matching profile, target TechCrunch/HBR/Medium. YouTube: In-market Education + Technology affinity. Testing: Month 1 equal budget, Month 2 double top 2 channels, Month 3 optimize by customer signal correlation. Target: LTV >$300 at CAC <$60.',
  },
  {
    id: 50,
    category: 'target-audience',
    title: 'Audience Expansion Strategy',
    difficulty: 'easy',
    points: 10,
    description: 'Plan how to expand into a new audience segment.',
    prompt: 'A personal finance app originally built for college students has saturated that market. They want to expand to young professionals (23-30) entering their first jobs. Outline the audience expansion strategy including messaging changes, channel shifts, and feature considerations.',
    hints: ['The new audience has different needs and maturity', 'Brand perception may help or hinder', 'Channel strategy changes as audience ages', 'Product may need feature additions', 'Messaging should evolve without alienating existing users'],
    criteria: [{ keyword: 'message|position|rebrand|evolve|tone', label: 'Adapts messaging' }, { keyword: 'channel|platform|media|where|reach', label: 'Shifts channels' }, { keyword: 'feature|product|function|add|adapt', label: 'Considers product changes' }, { keyword: 'young.professional|first.job|career|salary', label: 'Targets new segment' }, { keyword: 'exist|current|student|college|retain|both', label: 'Balances old and new audiences' }],
    sample_answer: 'Messaging: From "Manage your student budget" to "Master your money from day one." New themes: First salary management, student loan repayment, emergency fund, investing. Keep approachable tone, drop college language. Channels: Reduce campus ambassadors, increase LinkedIn presence, partner with career platforms, SEO for "budget first job." Features: Student loan tracking, 401(k) basics, salary negotiation tools, "First Paycheck" onboarding. Retention: App grows with users — "Level Up" email at graduation. Rollout: Month 1-2 new landing page, Month 3-4 new features, Month 5-6 full campaign on professional channels.',
  },
];

export function getExerciseById(id: number): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function getExercisesByCategory(categoryId: string): Exercise[] {
  return EXERCISES.filter((e) => e.category === categoryId);
}

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
